version: "3.8"

services:
  backend:
    build:
      context: ./taskmanager
    ports:
      - "8080:8080"
    networks:
      - tasknet

  backend-test:
    build: ./taskmanager
    command: ["mvn", "test"]
    networks:
      - tasknet

  frontend:
    build:
      context: ./TaskManager-UI
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tasknet

  frontend-test:
    build: ./TaskManager-UI
    command: ["npm", "test", "--", "--watchAll=false"]
    networks:
      - tasknet

networks:
  tasknet:
    driver: bridge
